name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main,staging]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.19'

    - name: Clean and install dependencies
      run: |
        go clean -modcache
        go mod download

    - name: Run tests
      run: go test -v ./...

    - name: Build binary
      run: go build -o quizard-users

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: quizard-users
        path: quizard-users
