on:
    push:
        branches:
            - staging
            - main
    pull_request:
      branches: [staging,main]
name: Security
jobs:
  Gosec:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v3
      - name: Run Gosec
        uses: securego/gosec@master
        with:
          args: ./...
